version: '3.7'

services:
  application:
    build: .
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    command: ["make", "start-app"]

  frontend:
    build: .
    volumes:
      - .:/app:delegated
    command: ["make", "start-frontend"]

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  reader-pgdata:
