version: '3.7'

services:
  application:
    build: .
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: ["make", "start-app"]

  frontend:
    build: .
    volumes:
      - .:/app:delegated
    command: ["make", "start-frontend"]

  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 54320:5432
    volumes:
    - reader-pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  reader-pgdata:
